= Dockerfile

...

== Overview

...
todo ... write description and brief (above)

== Prerequisites

This image has been developed and tested with Docker version 24.0.2 on top of Ubuntu 23.10.

== About the tags and versions

todo ...

== How to use this image

todo ... at least update the image names below

[source, bash]

----
docker build -t local/fantasy-hockey-app:dev .
docker run --rm -it -p 8080:8080 local/fantasy-hockey-app:dev
----

== See also

todo ... list all relevant information and links
