---
# @file playbook.yml
# @brief Antora playbook to generate the documentation pages for this repository
#
# @description ...
# todo ... write description
#
# NOTE: Remember that all paths referenced in this file should be present inside the Docker image.
# The files inside the Docker image are copied into the same folders as in the dev container. This
# means you have to run everything from inside the dev container.

site:
  title: Fantasy Hockey Documentation
  url: /docs
  start_page: fantasy-hockey::index.adoc
  robots: allow

content:
  branches: ['*', '!dependabot/*']
  # tags: [v*]
  sources:
    - url: /workspaces/fantasy-hockey
      start_path: components/docs

asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: https://github.com/sommerfeld-io/website/releases/download/v0.5.0/ui-bundle-0.5.0.zip
    snapshot: true

output:
  clean: true
  dir: /target/docs/public

runtime:
  cache_dir: /target/docs/cache
  fetch: true
