---
# @file pipeline.yml
# @brief Deployment pipeline for the Fantasy Hockey application.
#
# @description The deployment pipeline for the Fantasy Hockey App is implemented using GitHub
# Actions. The primary objective of this pipeline is to assess the releasability of the application
# for deployment with every push to the ``main`` branch. This is achieved through a series of
# automated tests and validations (performed on all branches, but the ``main`` branch carries the
# code thatshould be stable and production-ready). The workflow is designed to build every artifact
# of the Fantasy Hockey App and subject it to various types of tests to verify its functionality
# and integrity. If all tests are successful, indicating that the project is ready for release, a
# release candidate is generated and published to DockerHub.
#
# The deployment process for the Fantasy Hockey App utilizes Docker images. Images are built and
# unit tested. Each Snapshot image is tagged with the commit-sha, providing a clear reference to
# the version of the codebase from which it was generated, and subsequently pushed to DockerHub.
# Following this initial deployment, the Snapshot Docker images undergo further testing (security,
# performance, acceptance, etc.) to assess their performance and stability. If these additional
# tests pass successfully (and the workflow is running on the ``main`` branch), indicating that the
# Snapshot image is robust and reliable, it is then tagged as a release candidate. Notably, release
# candidates are exclusively published from the ``main`` branch.


name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - dependabot/**

env:
  IMAGE_TAG_RC: rc
  IMAGE_TAG_LATEST: latest

permissions:
  contents: read

jobs:

  # ----- Commit stage --------------------------

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: docker-compose --file docker-compose-lint.yml up yaml
        shell: bash

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run folderslint in container
        run: docker-compose --file docker-compose-lint.yml up folders
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ls-lint in container
        run: docker-compose --file docker-compose-lint.yml up filenames
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target

  validate-inspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate inspec profile
        run: docker-compose --file docker-compose-lint.yml up validate-inspec
        shell: bash

  build-images:
    runs-on: ubuntu-latest
    needs: ['lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'validate-inspec']
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    strategy:
      matrix:
        include:
          - REGISTRY: docker.io
            IMAGE_NAME: fantasy-hockey-app
            CONTEXT: components/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.CONTEXT }}/Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry ${{ matrix.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Build the Docker image and push to ${{ matrix.REGISTRY }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.CONTEXT }}
          platforms: linux/amd64
          push: true
          tags: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          provenance: true
          sbom: true
      - name: Docker Scout CVEs for :${{ github.sha }}
        uses: docker/scout-action@v1.3.0
        with:
          command: cves
          image: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ github.sha }}
          exit-code: false
          write-comment: ${{ github.event_name == 'pull_request' }}
      - name: Docker Scout Compare :${{ github.sha }} to :${{ env.IMAGE_TAG_RC }}"
        uses: docker/scout-action@v1.3.0
        with:
          command: compare
          image: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ github.sha }}
          to: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}
          exit-code: false
          write-comment: ${{ github.event_name == 'pull_request' }}

  # ----- Test stage ----------------------------

  # todo ... https://github.com/sommerfeld-io/fantasy-hockey/issues/12

  inspec-tests:
    runs-on: ubuntu-latest
    needs: ['build-images']
    if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
    strategy:
      matrix:
        include:
          - profile-name: app
            container-under-test: docker.io/sommerfeldio/fantasy-hockey-app:${{ github.sha }}
            container-ports: 8080:8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull ${{ matrix.container-under-test }}
        run: docker pull ${{ matrix.container-under-test }}
        shell: bash
      - name: Start ${{ matrix.container-under-test }}
        run: docker run --rm --name ${{ matrix.profile-name }} -d -p ${{ matrix.container-ports }} ${{ matrix.container-under-test }}
        shell: bash
      - name: Run Inspec tests
        run: |
          sleep 5s
          docker run --rm \
            --volume /var/run/docker.sock:/var/run/docker.sock  \
            --volume ./components/test/inspec:/inspec \
            --workdir /inspec \
            chef/inspec:5.22.36 exec ${{ matrix.profile-name }} --target docker://${{ matrix.profile-name }} --chef-license=accept-no-persist
        shell: bash
      - name: Stop ${{ matrix.container-under-test }}
        if: always()
        run: docker stop ${{ matrix.profile-name }}
        shell: bash

  # ----- Deploy :rc stage ----------------------

  publish-rc:
    runs-on: ubuntu-latest
    needs: ['inspec-tests']
    if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
    permissions: # see build-images (duplicated because github actions does not support anchors)
      contents: read
      pull-requests: write
      security-events: write
    strategy: # see build-images (duplicated because github actions does not support anchors)
      matrix:
        include:
          - REGISTRY: docker.io
            IMAGE_NAME: fantasy-hockey-app
            CONTEXT: components/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry ${{ matrix.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Re-tag image as release candicate (:${{ env.IMAGE_TAG_RC }}) and deploy to ${{ matrix.REGISTRY }}
        run: |
          SRC_IMAGE="${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ github.sha }}"
          TARGET_IMAGE="${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}"
          docker pull "$SRC_IMAGE"
          docker tag "$SRC_IMAGE" "$TARGET_IMAGE"
          docker push "$TARGET_IMAGE"
        shell: bash
      # todo ... https://github.com/sommerfeld-io/fantasy-hockey/issues/17
      # - name: Docker Scout Compare :${{ env.IMAGE_TAG_RC }}" to :${{ env.IMAGE_TAG_LATEST }}
      #   uses: docker/scout-action@v1.3.0
      #   with:
      #     command: compare
      #     image: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ env.IMAGE_TAG_RC }}
      #     to: ${{ matrix.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}
      #     exit-code: false
      #     write-comment: ${{ github.event_name == 'pull_request' }}

  # ----- Notifications -------------------------

  on-failure:
    runs-on: ubuntu-latest
    needs: [
      'lint-yaml',
      'lint-folders',
      'lint-filenames',
      'shellcheck',
      'validate-inspec',
      'build-images',
      'inspec-tests',
      'publish-rc',
    ]
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
