---
# @file pipeline.yml
# @brief Deployment pipeline for the Fantasy Hockey application.
#
# @description ...
# TODO ...This will become a deployment pipeline the way Dave Farley thinks of this.


name: Deployment Pipeline

on:
  push:
    branches:
      - main
    # branches-ignore:
    #   - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

env:
  GHCR: ghcr.io
  GHCR_USER: sommerfeld-io
  IMAGE_NAME: fantasy-hockey-app
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

permissions:
  contents: read

jobs:

  # ----- Commit stage --------------------------

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run yamllint
        run: make lint-yaml
        shell: bash

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run folderslint in container
        run: make lint-folders
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ls-lint in container
        run: make lint-filenames
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: node_modules target

  lint-makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run checkmake in container
        run: make lint-makefile
        shell: bash

  # ----- Build Stage ---------------------------

  build-app:
    runs-on: ubuntu-latest
    needs: ['lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-makefile']
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      REGISTRY_USER: sommerfeld-io
      REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: components/app/Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
      - name: Build the Docker image and push to ${{ env.REGISTRY }}
        uses: docker/build-push-action@v5
        with:
          context: components/app
          platforms: linux/amd64
          push: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          provenance: true
          sbom: true

  # ----- Test stage ----------------------------

  # todo ... inspec and all other tests
  # todo ... https://github.com/sommerfeld-io/fantasy-hockey/issues/12

  inspec:
    runs-on: ubuntu-latest
    needs: ['build-app']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # ----- Deploy :rc stage ----------------------

  publish-release-candidate:
    runs-on: ubuntu-latest
    needs: ['inspec']
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      packages: read
    env:
      REGISTRY: docker.io
      REGISTRY_USER: ${{ secrets.DOCKERHUB_USER }}
      REGISTRY_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}
      - name: Set docker tag
        id: vars
        run: echo "DOCKER_TAG=rc" >> $GITHUB_OUTPUT
        shell: bash
      - name: Re-tag image as release candicate (:${{ steps.vars.outputs.DOCKER_TAG }}) and deploy to ${{ env.REGISTRY }}
        run: |
          SRC_IMAGE="${{ env.GHCR }}/${{ env.GHCR_USER }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}"
          TARGET_IMAGE="${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.DOCKER_TAG }}"
          docker pull "$SRC_IMAGE"
          docker tag "$SRC_IMAGE" "$TARGET_IMAGE"
          docker push "$TARGET_IMAGE"
        shell: bash
      # todo ... https://github.com/sommerfeld-io/fantasy-hockey/issues/17
      # - name: Docker Scout Compare
      #   uses: docker/scout-action@v1.3.0
      #   with:
      #     command: compare
      #     image: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.DOCKER_TAG }}
      #     to: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
      #     exit-code: false
      #     write-comment: ${{ github.event_name == 'pull_request' }}
      - name: Docker Scout CVEs
        uses: docker/scout-action@v1.3.0
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.DOCKER_TAG }}
          # exit-code: ${{ github.event_name == 'pull_request' }}
          exit-code: false
          write-comment: ${{ github.event_name == 'pull_request' }}

  # ----- Notifications -------------------------

  on-failure:
    runs-on: ubuntu-latest
    needs: ['lint-yaml', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-makefile', 'build-app', 'inspec', 'publish-release-candidate']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
